name: deploy

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.x'  # Versão do Node.js que você deseja usar

    - name: Install dependencies
     run: |
          npm ci
          npm run build

      name: deploy
      with:
          publish_dir: ./build